### ISSUE TITLE
Missing pulse option,Unable to use irs

### ISSUE THREAD

**Issue by Zhaodaidai** [WSTxda/ViperFX-RE-Releases#11]
![QQ图片20240519235202](https://github.com/WSTxda/ViperFX-RE-Releases/assets/71388480/a24281f7-5d11-49f5-b2f7-d0fe7381fbab)
![QQ图片20240519235206](https://github.com/WSTxda/ViperFX-RE-Releases/assets/71388480/5e74c1d5-831f-4a86-b5bd-42568dbc0e68)
My device is oneplus 9pro, Android 14
viperFX works fine, but the irs and some options don't, even if I use headphones the options don't increase

I very much hope that this problem can be solved, thank you very much

**Comment by WSTxda** [comment]
Because it is not available on the driver side, the option is hidden in the application, as it has no real use

**Comment by Zhaodaidai** [comment]
That's it. I hope irs pulse will be added in the future.
