### ISSUE TITLE
DDC not work ?

### ISSUE THREAD

**Issue by MusaGujjar5** [WSTxda/ViperFX-RE-Releases#12]
Kindly any one can help DDC not work ...
![Screenshot_20240607-091536_ViPER4Android FX](https://github.com/WSTxda/ViperFX-RE-Releases/assets/172005272/269e8b88-be8a-4712-96e7-043633df8e16)
![Screenshot_20240607-091545_ViPER4Android FX](https://github.com/WSTxda/ViperFX-RE-Releases/assets/172005272/b4ae63a4-b2ec-45db-8af3-3e62aaa240ee)

**Comment by WSTxda** [comment]
For ddc to work, you must also copy the "kernel" files folder to the ViperFX data directory

**Comment by MusaGujjar5** [comment]
![Screenshot_20240607-092501_ES File Explorer](https://github.com/WSTxda/ViperFX-RE-Releases/assets/172005272/9527e885-c5ee-43f1-9ff0-e427603e363b)
![Screenshot_20240607-092432_ViPER4Android FX](https://github.com/WSTxda/ViperFX-RE-Releases/assets/172005272/1758f789-6a76-4c54-bb80-2c4107162250)

Still not work even present load app auto close...

**Comment by WSTxda** [comment]
check if this occurs in the original application
