### ISSUE TITLE
Driver not recognised in 6.6

### ISSUE THREAD

**Issue by rabaimorp** [WSTxda/ViperFX-RE-Releases#13]
After I updated the app to 6.6 the audio driver (magisk module) stopped beeing recognised, and the app says "No driver found" reinstalling the driver module haven't fixed it.
**ROM:**
LineageOS

**ROM Version:**
21-20240722-UNOFFICIAL-arm64_bvN

EDIT:
I've updated magisk at the same time at the app, so might be relevant.
**Magisk version:**
27006

**Comment by WSTxda** [comment]
In this case version 0.5.0 should work, you can install 0.6.1 after that

Out of curiosity, are you using an additional audio module? like AML or Dolby?

**Comment by rabaimorp** [comment]
Why? Whats the issue? Also do you mean the app or driver?

I'm not using additional audio modules.

**Comment by WSTxda** [comment]
Just referring to the driver, you can check if the official project app (distributed with the driver) has this problem
