### ISSUE TITLE
A few translate issue in language Simplified Chinese

### ISSUE THREAD

**Issue by Astoritin** [WSTxda/ViperFX-RE-Releases#15]
![Screenshot_20240819-143313_ViPER4Android FX](https://github.com/user-attachments/assets/4e072371-4194-4fc0-9450-cd8876f34724)
Usually we call 已启用 or 已激活 instead of 活性 in language Simplified Chinese to show users ViperFx is  enabled.
![Screenshot_20240819-143316_ViPER4Android FX](https://github.com/user-attachments/assets/0f7b01a4-2161-4bae-9d48-b5e2a7bc523f)
And we use 已禁用 or 未激活 instead of 残疾人 in language Simplified Chinese to show users ViperFx is disabled.

Thank you for your hard work which makes us enjoy the material design 3 UI in ViperFx very much : )

**Comment by WSTxda** [comment]
Fixed, new build will have this typo fix

**Comment by WSTxda** [comment]
Check latest version now

**Comment by Astoritin** [comment]
> Check latest version now

It fixed, thank you very much :)

**Comment by Astoritin** [comment]
> Check latest version now

It fixed, thank you very much :)
