### ISSUE TITLE
does not work with sony WH-10000XM5 Bluetooth AAC codec

### ISSUE THREAD

**Issue by wb1016** [WSTxda/ViperFX-RE-Releases#17]
using driver 0.6.1, and latest frontend.
with leagacy mode turned on, when playing YouTube video, driver status shows the driver is not enabled nor it is processing.
i tried changing codec to AptX but got no luck. and of course, i tried rebooting and restarting youtube app, and v4a frontend.

**Comment by WSTxda** [comment]
Check if there is another equalizer overlapping the v4a, It is worth mentioning that the driver does not need another support module, such as AML. and that although there are reports of v4a working with Dolby, it was not designed with this possibility in mind, then there may be some problems.

**Comment by wb1016** [comment]
i did not have any audio mods exept ACP.
