### ISSUE TITLE
App installation failed

### ISSUE THREAD

**Issue by MrStaten1** [WSTxda/ViperFX-RE-Releases#18]
![Screenshot_20240911-190750](https://github.com/user-attachments/assets/402cf693-0192-4404-bde4-837fd464cc1b)

**Comment by WSTxda** [comment]
Uninstall the previous version and install the new one, the sign key has been changed as advised in version 6.8

![Uploading Screenshot_2024-09-12-01-54-38-374_com.github.android-edit.jpg …]()
