### ISSUE TITLE
app cant detect youtube

### ISSUE THREAD

**Issue by MrHero118** [WSTxda/ViperFX-RE-Releases#19]
hey
the app and driver seems to be unable to detect sounds from youtube app. works on music and music players but doesn't work on any version on youtube app

**Comment by WSTxda** [comment]
enable legacy mode

**Comment by WSTxda** [comment]
enable legacy mode

**Comment by MrHero118** [comment]
legacy mode doesn't fix issue
instead of showing error "please play music or enable master" (as it shows in normal mode)
it shows all details but both enabled and processed options are no

**Comment by Graywizard888** [comment]
Working on my youtube sound
