### ISSUE TITLE
Can't Install App

### ISSUE THREAD

**Issue by Naveed-SNR** [WSTxda/ViperFX-RE-Releases#21]
Whenever I try installing the app, I get a message saying "App not installed as package conflicts with an existing package." I removed the older version and the old module before trying to install the latest one. I checked data/adb and sdcard/Android/data for any remnants from the previous install but I'm still not able to install the app. However, I had no issues flashing the module.

**Comment by WSTxda** [comment]
The apk signature has been changed for better distribution control, you need to do a clean installation. And if you use a custom ROM that comes pre-installed, you should contact the maintainer/developer.

If there is no conflict, the apk should be installed. and if there is, it is not from ViperFX side.

**Comment by Naveed-SNR** [comment]
> The apk signature has been changed for better distribution control, you need to do a clean installation. And if you use a custom ROM that comes pre-installed, you should contact the maintainer/developer.
> 
> If there is no conflict, the apk should be installed. and if there is, it is not from ViperFX side.

The custom ROM I got has Dolby pre-installed not viper and by clean I install I suppose u mean removing both the module and apk which I did but no luck.

**Comment by WSTxda** [comment]
Well this is really strange, there is no logical reason why this would not be installed.

**Comment by Naveed-SNR** [comment]
> Well this is really strange, there is no logical reason why this would not be installed.

Ikr, I changed the package name using some Apk Editor and it did work for some reason.
