### ISSUE TITLE
opening and closing settings freezes

### ISSUE THREAD

**Issue by Blaubeermuffin** [WSTxda/ViperFX-RE-Releases#3]
After installing version 6.0, if I try to open the settings nothing happens. 
I noticed though, that if I switch apps/go to my home screen and go back into the app, that the settings are now open. Same thing happened, if I try to leave the settings.

How to reproduce:
Open app and try opening the settings.

App version used: 6.0
Android version: 12
Phone: OnePlus 7 Pro (GM1913), running rooted stock Android

**Comment by WSTxda** [comment]
hello, thanks for report.

currently investigating the problem i discovered that it is the animation embedded in the activities.

i will fix it and release the build at some moment after test.

sorry for the inconvenience...

**Comment by WSTxda** [comment]
Check new release [6.1](https://github.com/WSTxda/ViperFX-RE-Releases/releases/tag/6.1)

**Comment by Blaubeermuffin** [comment]
Working again as intended. Thanks for the quick fix!
