### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by iscle** [WSTxda/ViperFX-RE-Releases#6]
Hi!

Just got this repo on my "Recommended" tab. I like the project, but some credits to Thomas and me would be nice :) We're the ones working on the original app.

Regards :)

**Comment by WSTxda** [comment]
Hi, thanks for your contact. Of course I can do this, the app's settings tab contains all the credits of all contributors to the project.

I only created this repository to publish builds along with a small setup guide, so I don't have credits or other information.

Thank you for the incredible work with V4A by the way. :)


![Screenshot_2024-03-02-00-26-19-716_com wstxda viper4android](https://github.com/WSTxda/ViperFX-RE-Releases/assets/37253994/12f8734b-7ebf-40b9-a6c8-180a12f69de2)

**Comment by iscle** [comment]
Thanks for the quick reply!

I was aware that we're mentioned in the app itself :) I meant on the repo README.md, I should have had specified hahaha

Adding a section at the end is enough for me :) But feel free to do it as you wish.

Thanks again, and good job with the redesign, I like it.

**Comment by WSTxda** [comment]
Ok, in this case it is done, let me know if you have any observations

1527de946a66c3af872038fc8507ed433730568d

**Comment by iscle** [comment]
Awesome, thanks!
