### ISSUE TITLE
Functional Requirements

### ISSUE THREAD

**Issue by MNDIA** [WSTxda/ViperFX-RE-Releases#7]
Functional Requirements
Can we **add an api to provide "load presets" operation**? I want to communicate information via terminal to viperfx，is it possible?Usage scenarios, for example, first, when Bluetooth is turned on or headphones are connected, and then a preset is automatically loaded.
Now I can use other tools to do the first detection, but I don’t know how to communicate with viperfx

**Comment by WSTxda** [comment]
Cannot make this
