### ISSUE TITLE
Make sure correct module is installed error. App version 6.2, driver 0.6.1 installed

### ISSUE THREAD

**Issue by Ibrohim112** [WSTxda/ViperFX-RE-Releases#8]
Samsung Galaxy S10 Oneui 3.1 An-11, magisk 23.0, installed viper4 re 0.6.1 module as it is latest, then installed latest release apk 6.2, reboot, opened it, Make sure correct module installed popup, ok. Checked magisk modules, there i installed it and it is en
![Screenshot_20240319-115654_ViPER4Android FX](https://github.com/WSTxda/ViperFX-RE-Releases/assets/94105067/fb828744-80a6-44f2-b9cd-5908969b7d15)
abled, recheck app, still this error,

**Comment by WSTxda** [comment]
Check you modules list, ViperFX cannot work with, dolby, AML, Sound Ehancer, etc.

**Comment by cygiel5420** [comment]
I am having the exact same issue. No other modules installed besides Viper. Fresh ROM install too
